name: Automatic Merge back
on:
  push:
    branches:
      - 'main'
      - 'mergeback'
      - 'release/*'
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/mergeback.js')
            await script({github, context, core})}
