name: Automatic Merge back
on:
  push:
    branches:
      - "*"
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get merged releases
        id: merged-releases
        run: |
          git fetch --all
          git branch -r --merged
          cat merged-releases.csv
        shell: bash
      # - uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const script = require('./.github/workflows/mergeback.js')
      #       await script({github, context, core})
